export const PaymentEscrowAbi = [
  {
    inputs: [
      {
        internalType: "contract SpendPermissionManager",
        name: "spendPermissionManager",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "uint16", name: "feeBps", type: "uint16" }],
    name: "FeeBpsOverflow",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "permissionHash", type: "bytes32" },
      { internalType: "uint256", name: "escrowedValue", type: "uint256" },
      { internalType: "uint160", name: "requestedValue", type: "uint160" },
    ],
    name: "InsufficientEscrow",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "address", name: "merchant", type: "address" },
    ],
    name: "InvalidRefundSender",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "expected", type: "address" },
    ],
    name: "InvalidSender",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "msgValue", type: "uint256" },
      { internalType: "uint256", name: "argValue", type: "uint256" },
    ],
    name: "NativeTokenValueMismatch",
    type: "error",
  },
  { inputs: [], name: "PermissionApprovalFailed", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "refund", type: "uint256" },
      { internalType: "uint256", name: "captured", type: "uint256" },
    ],
    name: "RefundExceedsCapture",
    type: "error",
  },
  { inputs: [], name: "ZeroFeeRecipient", type: "error" },
  { inputs: [], name: "ZeroValue", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "permissionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "PaymentAuthorized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "permissionHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "PaymentCaptured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "permissionHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "refunder",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "PaymentRefunded",
    type: "event",
  },
  {
    inputs: [],
    name: "NATIVE_TOKEN",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PERMISSION_MANAGER",
    outputs: [
      {
        internalType: "contract SpendPermissionManager",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
      { internalType: "uint160", name: "value", type: "uint160" },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "authorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
      { internalType: "uint160", name: "value", type: "uint160" },
    ],
    name: "capture",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "extraData", type: "bytes" }],
    name: "decodeExtraData",
    outputs: [
      { internalType: "address", name: "operator", type: "address" },
      { internalType: "address", name: "merchant", type: "address" },
      { internalType: "uint16", name: "feeBps", type: "uint16" },
      { internalType: "address", name: "feeRecipient", type: "address" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
      { internalType: "uint160", name: "value", type: "uint160" },
    ],
    name: "reauthorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
      { internalType: "uint160", name: "value", type: "uint160" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
      { internalType: "uint160", name: "value", type: "uint160" },
    ],
    name: "refundFromEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "account", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint160", name: "allowance", type: "uint160" },
          { internalType: "uint48", name: "period", type: "uint48" },
          { internalType: "uint48", name: "start", type: "uint48" },
          { internalType: "uint48", name: "end", type: "uint48" },
          { internalType: "uint256", name: "salt", type: "uint256" },
          { internalType: "bytes", name: "extraData", type: "bytes" },
        ],
        internalType: "struct SpendPermissionManager.SpendPermission",
        name: "permission",
        type: "tuple",
      },
    ],
    name: "void",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
