export const PaymentEscrowAbi = [
  {
    inputs: [
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      { internalType: "uint48", name: "expiry", type: "uint48" },
    ],
    name: "AfterAuthorizationExpiry",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      { internalType: "uint48", name: "expiry", type: "uint48" },
    ],
    name: "AfterPreApprovalExpiry",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      { internalType: "uint48", name: "expiry", type: "uint48" },
    ],
    name: "AfterRefundExpiry",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "limit", type: "uint256" },
    ],
    name: "AmountOverflow",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      { internalType: "uint48", name: "expiry", type: "uint48" },
    ],
    name: "BeforeAuthorizationExpiry",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "maxAmount", type: "uint256" },
    ],
    name: "ExceedsMaxAmount",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "feeBps", type: "uint16" },
      { internalType: "uint16", name: "minFeeBps", type: "uint16" },
      { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
    ],
    name: "FeeBpsOutOfRange",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint16", name: "feeBps", type: "uint16" }],
    name: "FeeBpsOverflow",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
      { internalType: "uint256", name: "authorizedAmount", type: "uint256" },
      { internalType: "uint256", name: "requestedAmount", type: "uint256" },
    ],
    name: "InsufficientAuthorization",
    type: "error",
  },
  { inputs: [], name: "InvalidCollectorForOperation", type: "error" },
  {
    inputs: [
      { internalType: "uint48", name: "preApproval", type: "uint48" },
      { internalType: "uint48", name: "authorization", type: "uint48" },
      { internalType: "uint48", name: "refund", type: "uint48" },
    ],
    name: "InvalidExpiries",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint16", name: "minFeeBps", type: "uint16" },
      { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
    ],
    name: "InvalidFeeBpsRange",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "attempted", type: "address" },
      { internalType: "address", name: "expected", type: "address" },
    ],
    name: "InvalidFeeReceiver",
    type: "error",
  },
  {
    inputs: [
      { internalType: "address", name: "sender", type: "address" },
      { internalType: "address", name: "expected", type: "address" },
    ],
    name: "InvalidSender",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
    ],
    name: "PaymentAlreadyCollected",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "refund", type: "uint256" },
      { internalType: "uint256", name: "captured", type: "uint256" },
    ],
    name: "RefundExceedsCapture",
    type: "error",
  },
  { inputs: [], name: "TokenCollectionFailed", type: "error" },
  { inputs: [], name: "ZeroAmount", type: "error" },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
    ],
    name: "ZeroAuthorization",
    type: "error",
  },
  { inputs: [], name: "ZeroFeeReceiver", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenCollector",
        type: "address",
      },
    ],
    name: "PaymentAuthorized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PaymentCaptured",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "payer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenCollector",
        type: "address",
      },
    ],
    name: "PaymentCharged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PaymentReclaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "tokenCollector",
        type: "address",
      },
    ],
    name: "PaymentRefunded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "paymentDetailsHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "PaymentVoided",
    type: "event",
  },
  {
    inputs: [],
    name: "PAYMENT_DETAILS_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenCollector", type: "address" },
      { internalType: "bytes", name: "collectorData", type: "bytes" },
    ],
    name: "authorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint16", name: "feeBps", type: "uint16" },
      { internalType: "address", name: "feeReceiver", type: "address" },
    ],
    name: "capture",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenCollector", type: "address" },
      { internalType: "bytes", name: "collectorData", type: "bytes" },
      { internalType: "uint16", name: "feeBps", type: "uint16" },
      { internalType: "address", name: "feeReceiver", type: "address" },
    ],
    name: "charge",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
    ],
    name: "getCapturableAmount",
    outputs: [{ internalType: "uint120", name: "", type: "uint120" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
    ],
    name: "getHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
    ],
    name: "getRefundableAmount",
    outputs: [{ internalType: "uint120", name: "", type: "uint120" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes32", name: "paymentDetailsHash", type: "bytes32" },
    ],
    name: "hasCollected",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
    ],
    name: "reclaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "address", name: "tokenCollector", type: "address" },
      { internalType: "bytes", name: "collectorData", type: "bytes" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "operator", type: "address" },
          { internalType: "address", name: "payer", type: "address" },
          { internalType: "address", name: "receiver", type: "address" },
          { internalType: "address", name: "token", type: "address" },
          { internalType: "uint256", name: "maxAmount", type: "uint256" },
          { internalType: "uint48", name: "preApprovalExpiry", type: "uint48" },
          {
            internalType: "uint48",
            name: "authorizationExpiry",
            type: "uint48",
          },
          { internalType: "uint48", name: "refundExpiry", type: "uint48" },
          { internalType: "uint16", name: "minFeeBps", type: "uint16" },
          { internalType: "uint16", name: "maxFeeBps", type: "uint16" },
          { internalType: "address", name: "feeReceiver", type: "address" },
          { internalType: "uint256", name: "salt", type: "uint256" },
        ],
        internalType: "struct PaymentEscrow.PaymentDetails",
        name: "paymentDetails",
        type: "tuple",
      },
    ],
    name: "void",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
